name: keptn-demo
on:
  workflow_dispatch:
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 11
          distribution: 'adopt'  # You can adjust the Java version as needed

  build_push:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean package
          ls -la
          ls -la target
          echo ${{ vars.DOCKER_REPO }}
          echo ${{ vars.DOCKER_USER }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ vars.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Container image
        run: docker build -t ${{ vars.DOCKER_REPO }}:${{ github.run_number }} .
      - name: Publish Docker image
        run: docker push ${{ vars.DOCKER_REPO }}:${{ github.run_number }}

